### ISSUE TITLE
Add a react example

### ISSUE THREAD

**Issue by albertmourato** [wedeploy/wedeploy-examples#18]
We only have react-native examples

**Comment by albertmourato** [comment]
I was planning to use https://github.com/facebook/create-react-app as @zenorocha suggested.
Look: https://react-reactreact.wedeploy.io/
wdt? @pragmaticivan

**Comment by pragmaticivan** [comment]
Sounds good to me 🍻

**Comment by albertmourato** [comment]
Done: 
https://github.com/wedeploy-examples/react-example
https://react.wedeploy.io/
