### ISSUE TITLE
Create Apache Zeppelin Example

### ISSUE THREAD

**Issue by vishal-reddy** [wedeploy/wedeploy-examples#33]
This service can be used to interact with WeDeploy Data Android Api in a notebook environment similar to Jupyter Notebook.

https://github.com/vishal-reddy/zeppelin-example

Issue moved from here since it didn't get checked out: https://github.com/wedeploy-examples/example-guidelines/issues/2

**Comment by albertmourato** [comment]
Done https://github.com/wedeploy-examples/zeppelin-example
Thanks a lot @vishal-reddy
