### ISSUE TITLE
Notify Albert and Jonni when a test fails on an example

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy-examples#6]
@jonnilundy: jonathan.lundy@liferay.com
@albertmourato: albertinin.mourato@liferay.com

**Comment by mdelapenya** [comment]
As discussed, we prefer email notifications over slack ones

**Comment by jonnilundy** [comment]
Hey @mdelapenya and @pragmaticivan, any status on this?

**Comment by mdelapenya** [comment]
Can we move this to the milestone? This way we can keep track of it more easily

**Comment by jonnilundy** [comment]
Nice! It might be better to add it next week since this milestone is almost over. Unless you feel like you can finish it today.

**Comment by mdelapenya** [comment]
Better for next one. I don't think I can have it today because of other tasks

**Comment by mdelapenya** [comment]
CI server configure to use Sendgrid for emails

@jonnilundy @albertmourato can you confirm you receive emails from the CI please?
