### ISSUE TITLE
Create a Kibana example

### ISSUE THREAD

**Issue by albertmourato** [wedeploy/wedeploy-examples#9]

**Comment by zenorocha** [comment]
Good idea, we need an ELK stack example

**Comment by albertmourato** [comment]
Done:
https://github.com/wedeploy-examples/kibana-example
https://kibana.wedeploy.io/

**Comment by zenorocha** [comment]
Can you rename this folder first https://github.com/wedeploy-examples/kibana-example/tree/master/elastic-search?  `elastic-search` > `elasticsearch`.

Also make sure you invite us to the example project on the Console.

**Comment by albertmourato** [comment]
@zenorocha updated! 
Thank you for the feedback!
